## ZARA CLOTHES
##### *Pricing Analysis*
##### *Aida Moure*
##### *March 2026*

In [1]:
# Import Essential Packages

import pandas as pd

* Import File

In [6]:
# Import Data

db=pd.read_csv("../data/zara_clothes.csv",sep=";") # the two points are to go up one level in github

#source: https://www.kaggle.com/datasets/nvarisha/zara-fashion-products-dataset-us-2024

In [7]:
db.head()

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19T08:50:05.654618,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,169.00,USD,2024-02-19T08:50:06.590930,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,129.00,USD,2024-02-19T08:50:07.301419,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,129.00,USD,2024-02-19T08:50:07.882922,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,139.00,USD,2024-02-19T08:50:08.453847,jackets,MAN

In [8]:
db.info() #no missing data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product ID        252 non-null    int64
 1   Product Position  252 non-null    object
 2   Promotion         252 non-null    object
 3   Product Category  252 non-null    object
 4   Seasonal          252 non-null    object
 5   Sales Volume      252 non-null    int64
 6   brand             252 non-null    object
 7   url               252 non-null    object
 8   sku               252 non-null    object
 9   name              251 non-null    object
 10  description       250 non-null    object
 11  price             252 non-null    float64
 12  currency          252 non-null    object
 13  scraped_at        252 non-null    object
 14  terms             252 non-null    object
 15  section           252 non-null    object
dtypes: float64(1), int64(2), object(13)
memory usage: 31.6+ KB

In [9]:
db.shape #252 rows, 16 columns

(252, 16)

In [10]:
db.duplicated().sum() #no duplicated rows

np.int64(0)

In [11]:
db.head()

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19T08:50:05.654618,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,169.00,USD,2024-02-19T08:50:06.590930,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,129.00,USD,2024-02-19T08:50:07.301419,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,129.00,USD,2024-02-19T08:50:07.882922,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,139.00,USD,2024-02-19T08:50:08.453847,jackets,MAN

In [12]:
#create a clean copy of the DB
dbclean= db.copy()

In [13]:
dbclean=dbclean.rename(columns={"Product ID":"id", "Product Position":"position","Promotion":"promotion", "Product Category":"category", "Seasonal":"seasonal", "Sales Volume":"salesvol"})

In [14]:
dbclean.head()

,id,position,promotion,category,seasonal,salesvol,brand,url,sku,name,description,price,currency,scraped_at,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19T08:50:05.654618,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,169.00,USD,2024-02-19T08:50:06.590930,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,129.00,USD,2024-02-19T08:50:07.301419,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,129.00,USD,2024-02-19T08:50:07.882922,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,139.00,USD,2024-02-19T08:50:08.453847,jackets,MAN

Check what values has each variable

In [15]:
dbclean.nunique() #number of unique values per variable

id             252
position         3
promotion        2
category         1
seasonal         2
salesvol       234
brand            1
url            228
sku            228
name           194
description    221
price           28
currency         1
scraped_at     229
terms            5
section          2
dtype: int64

In [16]:
dbclean.position.value_counts()

position
Aisle             97
End-cap           86
Front of Store    69
Name: count, dtype: int64

In [17]:
dbclean.promotion.value_counts()

promotion
No     132
Yes    120
Name: count, dtype: int64

In [18]:
dbclean.category.value_counts() #unnecessary variable

category
Clothing    252
Name: count, dtype: int64

In [19]:
dbclean.seasonal.value_counts()

seasonal
Yes    128
No     124
Name: count, dtype: int64

In [20]:
dbclean.salesvol.value_counts()

salesvol
1466    3
2220    2
1796    2
1145    2
1524    2
       ..
2973    1
1014    1
2222    1
2534    1
2870    1
Name: count, Length: 234, dtype: int64

In [21]:
dbclean.brand.value_counts() #unncessary variable

brand
Zara    252
Name: count, dtype: int64

In [22]:
dbclean.name.value_counts()

name
PLAID OVERSHIRT                          6
PATCH BOMBER JACKET                      4
POCKET OVERSHIRT                         4
FAUX LEATHER BOMBER JACKET               3
BOMBER JACKET                            3
                                        ..
RAISED TEXT T-SHIRT LIMITED EDITION      1
SEMI-SHEER KNIT SHIRT LIMITED EDITION    1
VISCOSE BLEND KNIT T-SHIRT               1
STRIPED JACQUARD T-SHIRT                 1
ABSTRACT PRINT KNIT T-SHIRT              1
Name: count, Length: 194, dtype: int64

In [23]:
dbclean.description.value_counts() #good for sentiment analysis

description
Varsity jacket with elastic collar and long sleeves. Welt pockets at hip and interior pocket. Embroidered appliqué and contrast front and back patches. Rib trim. Front snap button closure.              4
Lightweight jacket made of technical fabric. Round neck and long sleeves. Welt pockets at hip. Interior pocket. Rib trim. Front zip closure.                                                              2
Jacket made of technical fabric with padded interior. Tonal elastic rib high collar. Long sleeves. Welt pockets at hip and interior pocket. Interior elastic finish. Front zip closure.                   2
Overshirt made of stretchy fabric. Lapel collar and long sleeves with snap buttoned cuffs. Chest patch pockets. Front snap button closure.                                                                2
Slim fit jacket made of viscose blend fabric. Notched lapel collar. Long sleeves with buttoned cuffs. Welt pocket at chest and flap pockets at hip. Interior pocket. Back vents. Front button closure.    2
                                                                                                                                                                                                         ..
Slim fit shirt made of wrinkle effect fabric. Round neck and long sleeves.                                                                                                                                1
Knit shirt in viscose blend fabric. Mock neck and short sleeves. Rib trim.                                                                                                                                1
Relaxed fit T-shirt with round neck and short sleeves.                                                                                                                                                    1
Cotton knit T-shirt. Round neck and short sleeves.                                                                                                                                                        1
RETRO SNEAKERS                                                                                                                                                                                            1
Name: count, Length: 221, dtype: int64

In [24]:
dbclean.price.value_counts()

price
89.90     39
69.90     35
109.00    26
49.90     18
59.90     18
129.00    15
39.90     14
45.90     13
169.00    12
139.00    10
79.90      8
19.99      6
99.90      6
159.00     6
47.90      4
12.99      4
35.90      2
27.90      2
299.00     2
7.99       2
19.90      2
9.99       2
69.99      1
439.00     1
29.99      1
189.00     1
349.00     1
29.90      1
Name: count, dtype: int64

In [25]:
dbclean.currency.value_counts() #unnecesary variable

currency
USD    252
Name: count, dtype: int64

In [26]:
dbclean.terms.value_counts() #majority are jackets

terms
jackets     140
sweaters     41
t-shirts     32
shoes        31
jeans         8
Name: count, dtype: int64

In [27]:
dbclean.section.value_counts() #unbalanced

section
MAN      218
WOMAN     34
Name: count, dtype: int64

In [28]:
#remove unwanted vars
dbclean.drop(columns=["id","category", "brand", "currency", "sku", "scraped_at"], inplace=True)

In [29]:
dbclean=dbclean.dropna()

In [30]:
dbclean.shape #ok

(250, 10)

In [31]:
dbclean.columns

Index(['position', 'promotion', 'seasonal', 'salesvol', 'url', 'name',
       'description', 'price', 'terms', 'section'],
      dtype='object')